social_media:
  outputs:
    default:
      type: postgres
      threads: 4
      host: "{{ env_var('POSTGRES_HOST') }}"
      port: "{{ env_var('POSTGRES_PORT') | as_number }}"
      user: "{{ env_var('POSTGRES_ROLE_NAME') }}"
      pass: "{{ env_var('POSTGRES_ROLE_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DATABASE') }}"
      schema: default

  target: default